# 02 - Regression homework

In [2]:
import numpy as np
import pandas as pd
import matplotlib.pyplot as plt
import seaborn as sns
from matplotlib import pyplot as plt
%matplotlib inline

In [3]:
df = pd.read_csv('https://raw.githubusercontent.com/DataTalksClub/machine-learning-zoomcamp/main/cohorts/2026/data/car_fuel_efficiency_2026.csv')

In [4]:
df.head()

,model_year,origin,fuel_type,drivetrain,num_doors,engine_displacement,num_cylinders,horsepower,vehicle_weight,acceleration,fuel_efficiency_mpg
0,2006,Europe,Gasoline,Front-wheel drive,4,2180,6,243.0,3870,NaN,31.9
1,2008,Europe,Diesel,Front-wheel drive,4,2390,6,272.0,4210,NaN,31.3
2,1996,Asia,Gasoline,Front-wheel drive,5,2320,6,267.0,4240,17.3,27.5
3,1989,Europe,Gasoline,Front-wheel drive,4,2130,6,258.0,4490,18.7,28.5
4,1994,USA,Diesel,Front-wheel drive,3,2580,7,304.0,4510,17.5,31.0

In [5]:
df.isnull().sum()

model_year               0
origin                   0
fuel_type                0
drivetrain               0
num_doors                0
engine_displacement      0
num_cylinders            0
horsepower             877
vehicle_weight           0
acceleration           264
fuel_efficiency_mpg      0
dtype: int64

In [6]:
horsepower = df['horsepower']
horsepower.median()

np.float64(254.0)

In [7]:
n = len(df)
n_val = int(n * 0.2)
n_test = int(n * 0.2)
n_train = n - n_val - n_test

np.random.seed(42)
idx = np.arange(n)
np.random.shuffle(idx)

df_train = df.iloc[idx[:n_train]]
df_val = df.iloc[idx[n_train:n_train + n_val]]
df_test = df.iloc[idx[n_train + n_val:]]

print(len(df_train),
len(df_val),
len(df_test))

6000 2000 2000

In [8]:
base = df[['engine_displacement',
'horsepower',
'vehicle_weight',
'model_year',]]
base.head()

   engine_displacement  horsepower  vehicle_weight  model_year
0                 2180       243.0            3870        2006
1                 2390       272.0            4210        2008
2                 2320       267.0            4240        1996
3                 2130       258.0            4490        1989
4                 2580       304.0            4510        1994

In [9]:
df_train['fuel_efficiency_mpg']

6252    32.5
4684    29.1
1731    34.1
4742    30.6
4521    30.7
        ...
7895    29.8
9590    25.1
7288    27.7
278     31.6
3252    28.0
Name: fuel_efficiency_mpg, Length: 6000, dtype: float64

In [10]:
x_train = df_train[['engine_displacement',
'horsepower',
'vehicle_weight',
'model_year',]].fillna(0)

y_train = df_train['fuel_efficiency_mpg']

In [11]:
def train_linear_regression(X, y):
    ones = np.ones(X.shape[0])
    X = np.column_stack([ones, X])

    XTX = X.T.dot(X)
    XTX_inv = np.linalg.inv(XTX)
    w_full = XTX_inv.dot(X.T).dot(y)

    return w_full[0], w_full[1:]

In [12]:
def rmse(y, y_pred):
    se = (y - y_pred) ** 2
    mse = se.mean()
    return np.sqrt(mse)

In [13]:
w0, w = train_linear_regression(x_train, y_train)

y_pred = w0 + x_train.dot(w)
round(rmse(y_train, y_pred), 2)

np.float64(2.2)

In [20]:
def train_linear_regression_reg(X, y, r):
    ones = np.ones(X.shape[0])
    X = np.column_stack([ones, X])

    XTX = X.T.dot(X)
    XTX = XTX + r*np.eye(XTX.shape[0])
    XTX_inv = np.linalg.inv(XTX)
    w_full = XTX_inv.dot(X.T).dot(y)

    return w_full[0], w_full[1:]

In [21]:
x_val = df_val[['engine_displacement',
'horsepower',
'vehicle_weight',
'model_year',]].fillna(0)

y_val = df_val['fuel_efficiency_mpg']

for r in [0, 0.01, 0.1, 1, 5, 10, 100]:
    w0, w = train_linear_regression_reg(x_train, y_train, r)
    y_pred = w0 + x_val.dot(w)
    print(r, round(rmse(y_val, y_pred), 2))

0 2.21
0.01 2.21
0.1 2.22
1 2.35
5 2.41
10 2.42
100 2.43

In [30]:
n = len(df)
n_val = int(n * 0.2)
n_test = int(n * 0.2)
n_train = n - n_val - n_test
scores = np.zeros(10)


for x in range(10):
    np.random.seed(x)
    idx = np.arange(n)
    np.random.shuffle(idx)

    df_train = df.iloc[idx[:n_train]]
    df_val = df.iloc[idx[n_train:n_train + n_val]]
    df_test = df.iloc[idx[n_train + n_val:]]

    x_train = df_train[['engine_displacement',
    'horsepower',
    'vehicle_weight',
    'model_year',]].fillna(0)
    y_train = df_train['fuel_efficiency_mpg']

    x_val = df_val[['engine_displacement',
        'horsepower',
        'vehicle_weight',
        'model_year',]].fillna(0)
    y_val = df_val['fuel_efficiency_mpg']

    w0, w = train_linear_regression(x_train, y_train)

    y_pred = w0 + x_val.dot(w)
    d = rmse(y_val, y_pred)
    scores[x] = d
std = round(np.std(scores),3)
print(std)

0.029

In [34]:
np.random.seed(9)
idx = np.arange(n)
np.random.shuffle(idx)

df_train = df.iloc[idx[:n_train]]
df_val = df.iloc[idx[n_train:n_train + n_val]]
df_test = df.iloc[idx[n_train + n_val:]]

x_train = df_train[['engine_displacement',
'horsepower',
'vehicle_weight',
'model_year',]].fillna(0)
y_train = df_train['fuel_efficiency_mpg']

x_val = df_val[['engine_displacement',
    'horsepower',
    'vehicle_weight',
    'model_year',]].fillna(0)
y_val = df_val['fuel_efficiency_mpg']

x_train_val = pd.concat([x_val, x_train])
x_train_val.reset_index()
y_train_val = pd.concat([y_val, y_train])
y_train_val.reset_index()

x_test = df_test[['engine_displacement',
    'horsepower',
    'vehicle_weight',
    'model_year',]].fillna(0)
y_test = df_test['fuel_efficiency_mpg']




w0, w = train_linear_regression_reg(x_train_val, y_train_val, r=0.001)

y_pred = w0 + x_test.dot(w)
d = rmse(y_test, y_pred)
print(round(d, 3))

2.236